### PR TITLE
62 example fa2

### PR DESCRIPTION
**Pull request by repype**

### CODE REVIEW

**Review by eliodemollari — APPROVED** [review]
locally tested

**Review by MikeHerman19 — COMMENTED** [review]
tested successfully

**Comment by amrap030** [comment]
Hey I also tested it, but I get the following error:

Bildschirmfoto 2021-11-21 um 14 01 50

Does this has anything to do with Windows folders? I am using a Mac.

**Comment by repype** [comment]
> Hey I also tested it, but I get the following error:
> 
> Bildschirmfoto 2021-11-21 um 14 01 50
> 
> Does this has anything to do with Windows directories? I am using a Mac.
> 
> The error is on the compile script:
> 
> `"compile": "docker run --rm -v \"%CD%\":/cd -w /cd ligolang/ligo:0.29.0 compile contract ./contracts/src/fa2_nft_asset.mligo -e nft_asset_main > ./contracts/out/fa2_nft_asset.tz",`

Yes, that seems to be OS specific, as it should work by using this command instead: `docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.29.0 compile contract ./contracts/src/fa2_nft_asset.mligo -e nft_asset_main > ./contracts/out/fa2_nft_asset.tz` on Linux or OSX, but I cant test it on my machine. See [here](https://ligolang.org/docs/intro/installation#dockerised-installation-recommended). Anyway, this problem should be fixed by setting up the local environment in #69.

**Comment by amrap030** [comment]
> docker run --rm -v "$PWD":"$PWD" -w "$PWD" ligolang/ligo:0.29.0 compile contract ./contracts/src/fa2_nft_asset.mligo -e nft_asset_main > ./contracts/out/fa2_nft_asset.tz

This still didn't work for me, no matter if I use single or double quotes. However, I managed to compile it with:

`"compile": "docker run --rm -v $PWD:$PWD -w $PWD ligolang/ligo:0.29.0 compile contract ./contracts/src/fa2_nft_asset.mligo -e nft_asset_main > ./contracts/out/fa2_nft_asset.tz"`

This doesn't use any quotes for `$PWD`.

**Comment by amrap030** [comment]
When running the deploy command, I get the following error:

```
Error: Unsupported key type
    at new InMemorySigner (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:413:27)
    at Function.<anonymous> (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:428:51)
    at step (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:61:27)
    at Object.next (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:42:57)
    at fulfilled (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:32:62)
```

I logged out the `FAUCET` and `ALICE_SECRET` and it is correctly parsed. I don't know what's wrong here.

**Comment by repype** [comment]
> When running the deploy command, I get the following error:
> 
> ```
> Error: Unsupported key type
>     at new InMemorySigner (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:413:27)
>     at Function.<anonymous> (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:428:51)
>     at step (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:61:27)
>     at Object.next (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:42:57)
>     at fulfilled (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:32:62)
> ```
> 
> I logged out the `FAUCET` and `ALICE_SECRET` and it is correctly parsed. I don't know what's wrong here.
> 
> This is my .env file:
> 
> ```
> ALICE_SECRET=d3a7eaf7b6d71b427389ed399bcf9a0ddf61759f
> FAUCET={"mnemonic": ["rabbit", "organ", "angle", "depend", "scheme", "damage", "reward", "junior", "soldier", "oak", "village", "exhaust", "wood", "enemy", "must"], "secret": "d3a7eaf7b6d71b427389ed399bcf9a0ddf61759f", "amount": "18688711552", "pkh": "tz1hb3K9MrvujxezNzw5UYdqKhwGS1fnZ2k2", "password": "co1nCOsSsB", "email": "synewgvx.pvaynzjo@tezos.example.org"}
> ```

Did you use the value after `unencrypted: ...`? Seems like the value of `ALICE_SECRET` has invalid format

**Comment by amrap030** [comment]
> > When running the deploy command, I get the following error:
> > ```
> > Error: Unsupported key type
> >     at new InMemorySigner (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:413:27)
> >     at Function.<anonymous> (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:428:51)
> >     at step (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:61:27)
> >     at Object.next (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:42:57)
> >     at fulfilled (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:32:62)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I logged out the `FAUCET` and `ALICE_SECRET` and it is correctly parsed. I don't know what's wrong here.
> > This is my .env file:
> > ```
> > ALICE_SECRET=d3a7eaf7b6d71b427389ed399bcf9a0ddf61759f
> > FAUCET={"mnemonic": ["rabbit", "organ", "angle", "depend", "scheme", "damage", "reward", "junior", "soldier", "oak", "village", "exhaust", "wood", "enemy", "must"], "secret": "d3a7eaf7b6d71b427389ed399bcf9a0ddf61759f", "amount": "18688711552", "pkh": "tz1hb3K9MrvujxezNzw5UYdqKhwGS1fnZ2k2", "password": "co1nCOsSsB", "email": "synewgvx.pvaynzjo@tezos.example.org"}
> > ```
> 
> Did you use the value after `unencrypted: ...`? Seems like the value of `ALICE_SECRET` has invalid format

Ok after reading the instructions correctly again I see my mistake. I forgot to run `yarn run sandbox-info`. Can you explain, what happens here? Where do these usable accounts come from? I thought we are using the FAUCET account here?

**Review by MikeHerman19 — APPROVED** [review]

**Comment by repype** [comment]
> > > When running the deploy command, I get the following error:
> > > ```
> > > Error: Unsupported key type
> > >     at new InMemorySigner (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:413:27)
> > >     at Function.<anonymous> (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:428:51)
> > >     at step (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:61:27)
> > >     at Object.next (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:42:57)
> > >     at fulfilled (/Users/kevinhertwig/uni/module/WS2122/adsp/taia-x/contracts/node_modules/@taquito/signer/dist/taquito-signer.umd.js:32:62)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I logged out the `FAUCET` and `ALICE_SECRET` and it is correctly parsed. I don't know what's wrong here.
> > > This is my .env file:
> > > ```
> > > ALICE_SECRET=d3a7eaf7b6d71b427389ed399bcf9a0ddf61759f
> > > FAUCET={"mnemonic": ["rabbit", "organ", "angle", "depend", "scheme", "damage", "reward", "junior", "soldier", "oak", "village", "exhaust", "wood", "enemy", "must"], "secret": "d3a7eaf7b6d71b427389ed399bcf9a0ddf61759f", "amount": "18688711552", "pkh": "tz1hb3K9MrvujxezNzw5UYdqKhwGS1fnZ2k2", "password": "co1nCOsSsB", "email": "synewgvx.pvaynzjo@tezos.example.org"}
> > > ```
> > 
> > 
> > Did you use the value after `unencrypted: ...`? Seems like the value of `ALICE_SECRET` has invalid format
> 
> Ok after reading the instructions correctly again I see my mistake. I forgot to run `yarn run sandbox-info`. Can you explain, what happens here? Where do these usable accounts come from? I thought we are using the FAUCET account here?

When starting the sandbox, 2 default accounts - Alice and Bob - are created. These accounts differ from the faucet because the faucet is only used on public testnets. Alice and Bob are comparable to the 10 default accounts when using Ganache as local Ethereum Blockchain.

**Comment by alvaro-alonso** [comment]
When using the `.env` values from [this comment](https://github.com/taia-x/taia-x/pull/68#issuecomment-974843912). I still get following message:

Screen Shot 2021-11-21 at 19 28 49

The how the `.env` is configure is also not ideal. For example:
- if I provide ALICE_SECRET why do I need to still provide a real account? This should be reworked
- Is it a good practice to put a raw json string in `.env`? 

And there is still [this problem ](https://github.com/taia-x/taia-x/pull/68#issuecomment-974817549)

**Comment by amrap030** [comment]
@repype @MikeHerman19 @eliodemollari has anyone worked on these bugs and optimizations?

**Comment by eliodemollari** [comment]
@amrap030 after having a short talk, we decided not to continue working on this ticket because it was just an example that maybe we are not going to use at all, and it doesn't make sense to invest time fixing bugs or optimizing it.

**Comment by amrap030** [comment]
> @amrap030 after having a short talk, we decided not to continue working on this ticket because it was just an example that we are not going to use at all, and it doesn't make sense to invest time fixing bugs or optimizing it. As you can see in this [Issue](https://github.com/taia-x/taia-x/issues/62#issuecomment-979090986), I'm only waiting for the confirmation of @repype, @MikeHerman19 to complete close this Issue

@eliodemollari can we close this, with or without merge?

**Pull request closed without merging**
