### PR TITLE
#115 provider node

### PR DESCRIPTION
**Pull request by kaustabhbarman**

### CODE REVIEW

**Comment by alvaro-alonso** [comment]
@kaustabhbarman did you have a look at the `backend` directory? Inside there is a working api, with the config management and the docker setup with automatic database connection. It seems to me you started a whole new component instead of building up on what is already being done. 

I think is good that you added alembic to the project. but why not:
- add alembic to the project
- add the routes to the project

I can rename the `backend` to `provider` like it was originially. In the branch I am working.

**Review by alvaro-alonso — CHANGES_REQUESTED** [review]
@kaustabhbarman did you have a look at the `backend` directory? Inside there is a working api, with the config management and the docker setup with automatic database connection. It seems to me you started a whole new component instead of building up on what is already being done. 

I think is good that you added alembic to the project. but why not:
- add alembic to `backend`
- add the routes to `backend`

I can rename the `backend` to `provider` like it was originially. In the branch I am working.

**Comment by kaustabhbarman** [comment]
> @kaustabhbarman did you have a look at the `backend` directory? Inside there is a working api, with the config management and the docker setup with automatic database connection. It seems to me you started a whole new component instead of building up on what is already being done.
> 

I did that because I was working on FastAPI for the first time and it was quite confusing for me how the things were connected in backend. So that's why I started a new component to do it from scratch for better understanding. I have the intention to merge it to backend dir.

**Comment by amrap030** [comment]
@kaustabhbarman @alvaro-alonso I did some extensive refactoring, because we actually only need these two api endpoints for now. We can do some more refactoring by generating a router folder for example. I am not a python programmer so @alvaro-alonso if you have more ideas on how to make this cleaner and more dynamic (the `artifactUri` for example is now hardcoded with `localhost`). I would suggest that we can merge this for now, because it works and that is the most important for me at the moment. In the next days/weeks we can improve this and add the database connection.

**Comment by alvaro-alonso** [comment]
Hello hello,

I just read your comments, and I assume it was decided last week to keep the data in files rather than in a DB. That is fine for me, but am I not sure why you are deleting the `config.py` (this loads the Variables from the `.env` file) nor the `db.py` module (this creates the connection to the DB). We need those for the access control.  @kaustabhbarman @amrap030

**Pull request closed without merging**
