### PR TITLE
118 contracts refactoring

### PR DESCRIPTION
**Pull request by repype**
@eliodemollari Please pay special attention to the deploy script (and the paths) on macOS

### CODE REVIEW

**Review by MikeHerman19 — COMMENTED** [review]
worked on windows

**Comment by eliodemollari** [comment]
LGTM, with minimal changes on some paths

**Review by eliodemollari — APPROVED** [review]
LGTM, with minimal changes on some paths

**Comment by repype** [comment]
> LGTM, with minimal changes on some paths

@eliodemollari Could you explain that in more detail? As mentioned before, I don't know if setting an absolute path (see [here in line 8](https://github.com/taia-x/taia-x/pull/121/commits/ebb98653a2de7dbf6d4ce35d577b3c3234ebc262#diff-dc5b921443af037075633b3c6a7b4b5b96ea6d57821a018e8130c6c6c0cf99a8R8) and [here in line 31](https://github.com/taia-x/taia-x/pull/121/commits/ebb98653a2de7dbf6d4ce35d577b3c3234ebc262#diff-dc5b921443af037075633b3c6a7b4b5b96ea6d57821a018e8130c6c6c0cf99a8R31)) fixes the differences between macOS and Windows when importing the files in the deploy script. I have tried to work around this, but I can't test it because I don't have a Macbook

**Comment by eliodemollari** [comment]
@repype I was pointing to the wrong `.env`. So the paths seem to work fine now. But I get a the following error:
```
HttpResponseError {
  message: 'Http error response: (500) [{"kind":"branch","id":"proto.011-PtHangz2.implicit.empty_implicit_contract","implicit":"tz1W9E5TgV8XkBwDfocTwoSH4iCfUR9jVyTM"}]\n',
  status: 500,
  statusText: 'Internal Server Error',
  body: '[{"kind":"branch","id":"proto.011-PtHangz2.implicit.empty_implicit_contract","implicit":"tz1W9E5TgV8XkBwDfocTwoSH4iCfUR9jVyTM"}]\n',
  url: 'https://rpc.tzkt.io/hangzhou2net/chains/main/blocks/head/helpers/scripts/run_operation',
  name: 'HttpResponse'
}
```

**Comment by repype** [comment]
> @repype I was pointing to the wrong `.env`. So the paths seem to work fine now. But I get a the following error:
> 
> ```
> HttpResponseError {
>   message: 'Http error response: (500) [{"kind":"branch","id":"proto.011-PtHangz2.implicit.empty_implicit_contract","implicit":"tz1W9E5TgV8XkBwDfocTwoSH4iCfUR9jVyTM"}]\n',
>   status: 500,
>   statusText: 'Internal Server Error',
>   body: '[{"kind":"branch","id":"proto.011-PtHangz2.implicit.empty_implicit_contract","implicit":"tz1W9E5TgV8XkBwDfocTwoSH4iCfUR9jVyTM"}]\n',
>   url: 'https://rpc.tzkt.io/hangzhou2net/chains/main/blocks/head/helpers/scripts/run_operation',
>   name: 'HttpResponse'
> }
> ```

@eliodemollari Ok, that's great! The error you got I had as well. As a fix, I had to deposit funds into the account that I use to deploy the contract (from the .env file). I did that for example with [this](https://t.me/tezos_faucet_bot) telegrambot.

**Pull request merged**
