### PR TITLE
66: Role based Access management

### PR DESCRIPTION
**Pull request by MikeHerman19**

### CODE REVIEW

**Comment by amrap030** [comment]
If your intention is to let everyone call the functions, I would suggest removing the parameter address, that is passed to the functions. Instead, use the address of the one who calls the method. If the method should not be called by everyone, I would suggest to add an owner to the contract, and only let the owner call these methods. In this case, an address parameter makes sense. Additionally make sure, that no address can be multiple times in a mapping.

**Comment by repype** [comment]
> If your intention is to let everyone call the functions, I would suggest removing the parameter address, that is passed to the functions. Instead, use the address of the one who calls the method. If the method should not be called by everyone, I would suggest to add an owner to the contract, and only let the owner call these methods. In this case, an address parameter makes sense. Additionally make sure, that no address can be multiple times in a mapping.

Removed address parameter and now using `Tezos.sender` as userAddress in commit [a25869d](https://github.com/taia-x/taia-x/pull/72/commits/a25869db944b31d2a9a13e579c24d3df9b02f3f0).
**Besides that, we should think about permissions to registration for the specific roles** (e.g. should everyone become a provider/certifier/consumer?; how could a registration process - if needed - look like?)

**Comment by amrap030** [comment]
> > If your intention is to let everyone call the functions, I would suggest removing the parameter address, that is passed to the functions. Instead, use the address of the one who calls the method. If the method should not be called by everyone, I would suggest to add an owner to the contract, and only let the owner call these methods. In this case, an address parameter makes sense. Additionally make sure, that no address can be multiple times in a mapping.
> 
> Removed address parameter and now using `Tezos.sender` as userAddress in commit [a25869d](https://github.com/taia-x/taia-x/pull/72/commits/a25869db944b31d2a9a13e579c24d3df9b02f3f0). **Besides that, we should think about permissions to registration for the specific roles** (e.g. should everyone become a provider/certifier/consumer?; how could a registration process - if needed - look like?)

Thanks for the contribution. Currently the implementation of the registration proccess looks like the following: User clicks in signup -> User chooses role -> User connects to wallet -> respective function is called -> User is in respective Role mapping

However, I am actually starting to think about, wether the entire role system is necessary? Do we have any reasons, why we should have a role system? Especially, if everyone can assign a role to oneself, I am not sure if it makes sense.

**Comment by amrap030** [comment]
@repype @eliodemollari  can you give your approval, so that we can merge it to main? I think for the MVP, the current state is fine.

**Review by repype — APPROVED** [review]

**Review by eliodemollari — APPROVED** [review]
I think too that for the MVP, it should be fine.

**Pull request merged**
